workspace:
  base: /go
  path: src/github.com/justinbarrick/flux-operator

pipeline:
  test:
    image: justinbarrick/drone-minikube:localkube
    secrets: [ SSH_KEY ]
    environment:
      - KUBECONFIG=/go/.kube/config
      - DOCKER_HOST=tcp://minikube:2375
    commands:
      - ./integration-test.sh
    when:
      event: [push, tag]
      ref:
        exclude: [refs/tags/flux-sync-*]

services:
  minikube:
    image: justinbarrick/drone-minikube:localkube
    privileged: true
    commands:
    - echo nameserver 8.8.8.8 > /etc/resolv.conf
    - /usr/local/bin/docker-entrypoint.sh start
    when:
      event: [push, tag]
      ref:
        exclude: [refs/tags/flux-sync-*]
