apiVersion: "flux.codesink.net/v1alpha1"
kind: "Flux"
metadata:
  name: "example"
  namespace: default
spec:
  gitUrl: ssh://git@github.com/justinbarrick/flux-operator
  gitBranch: master
  gitPath: deploy/flux-example/
  gitPollInterval: 0m30s
  fluxImage: justinbarrick/flux
  fluxVersion: latest
  args:
    flux-namespace: default
  helmOperator:
    enabled: false
    chartPath: deploy/chart-example/
  tiller:
    enabled: false
  clusterRole:
    enabled: false
  role:
    enabled: true
  fluxCloud:
    enabled: true
    githubUrl: https://github.com/justinbarrick/flux-operator
    slackUrl: https://example.com/
    slackChannel: "#mychannel"
